########################################################################
########################################################################
"""
kmer_convert.py


Title: Unpublished work

By: J. A. Marchand

Converts Xenomorph kmer table to ONT kmer table 

Updated: 8/5/23
"""
########################################################################
########################################################################

import pandas as pd
import os
import glob
import pysam
from pathlib import Path


#### Import kmer model generated by Xenomorph pipeline 
kmer_model_input_file = #### 
kmers = pd.read_csv(kmer_model_input_file)

#Set an output model path
output_file_path = 'kmers/4mer_converted_model.csv'

#Statistic to use for generating model 
level_type = 'Mean level'



kmer_convert_file = open(output_file_path,'w')
for i in range(0,len(kmers)): 
    content = kmers.iloc[i]['KXmer']+' '+str(kmers.iloc[i][level_type])
    print(content)
    kmer_convert_file.write((content)+'\n')


kmer_convert_file.close()

