########################################################################
########################################################################
"""
kmer_convert.py
A tool to quickly convert xenomorph model files to remora model format. 

By: J. A. Marchand

Converts Xenomorph kmer table to ONT kmer table 

Updated: 8/5/23
"""
########################################################################
########################################################################

import pandas as pd
import os
import glob
import pysam
from pathlib import Path


#### Import kmer model generated by Xenomorph pipeline 
kmer_model_input_file = '/home/marchandlab/Dev/xenomorph-xemora/xx-test/BSn_10.4.1_Model_Building/BSn_10.4.1_Model_Building_FLG001_summary.csv'
kmers = pd.read_csv(kmer_model_input_file)

#Set an output model path
output_file_path ='/home/marchandlab/Dev/xenomorph-xemora/models/10.4.1/B_r10.4.1.csv'

#Statistic to use for generating model 
level_type = 'Mean level'

#For tombo2filter - which base required
xna_base = 'B'

def xeno2remora(output_file_path, level_type, kmers) : 
	kmer_convert_file = open(output_file_path,'w')
	for i in range(0,len(kmers)): 
		content = kmers.iloc[i]['KXmer']+' '+str(kmers.iloc[i][level_type])
		print(content)
		kmer_convert_file.write((content)+'\n')
	kmer_convert_file.close()


def xeno2filter(output_file_path, kmers, xna_base) : 
	print(kmers)
	filtered_kmers = kmers[kmers['KXmer'].str.contains(xna_base)].reset_index(drop=True)
	filtered_kmers = filtered_kmers.loc[:, ~filtered_kmers.columns.str.contains('^Unnamed')]

	filtered_kmers.to_csv(output_file_path, index = False)
	
print(kmers)
xeno2filter(output_file_path, kmers, xna_base)
	

